import torch
from pytorch_lightning import LightningModule

from darts.models.forecasting.nf_model import NeuralForecastModel, _NeuralForecastModule
from darts.utils.data.torch_datasets.utils import TorchTrainingSample
from engressionts.losses.energy_score import energy_score_loss


class _EngressionPLModule(_NeuralForecastModule):
    """
    Custom PyTorch Lightning Module that inherits from Darts' _NeuralForecastModule.
    This module overrides the training and validation step to explicitly compute the
    Energy Score loss against the multiple samples generated by NFEngressionBaseModel.
    """

    @property
    def supports_probabilistic_prediction(self) -> bool:
        return True

    def on_predict_start(self) -> None:
        super().on_predict_start()
        if hasattr(self.nf, "noise_layer") and self.nf.noise_layer is not None:
            seed = torch.initial_seed()
            self.nf.noise_layer.reset_seed(seed)

    def _train_val_step(self, batch, name: str, criterion, metrics) -> torch.Tensor:
        (
            past_target,
            past_covariates,
            historic_future_covariates,
            future_covariates,
            static_covariates,
            sample_weight,
            future_target,
        ) = batch

        M = self.nf.num_samples_train

        # Duplicate the batch items to create M samples for each input window.
        # This matches the behavior of _repeat_tensor in NFEngressionBaseModel.training_step().
        def repeat(t):
            return t.repeat_interleave(M, dim=0) if t is not None else None

        x_in_repeated = (
            repeat(past_target),
            repeat(past_covariates),
            repeat(historic_future_covariates),
            repeat(future_covariates),
            repeat(static_covariates),
            repeat(future_target) if name == "train" else None,
        )

        # Generate train output. This calls EnPatchTST's forward pass,
        # which internally adds noise.
        output = self._produce_train_output(x_in_repeated)

        # Output shape is currently flattened along the batch dimension: (B * M, H, C)
        # Or sometimes (B * M, H, C, 1) depending on target dimensions.
        B = future_target.shape[0]
        H = future_target.shape[1]
        C = future_target.shape[2]

        if output.dim() == 4 and output.shape[-1] == 1:
            output = output.squeeze(-1)

        # Reshape to (B, M, H, C) and permute to (M, B, H, C) for Energy Score calculation.
        samples = output.contiguous().view(B, M, H, C).permute(1, 0, 2, 3)

        # Mask is typically all ones as Darts filters out missing values before batching
        mask = torch.ones_like(future_target)

        # Compute Energy Score loss directly to avoid conflict with PyTorch/NeuralForecast __call__
        # The current energy_score_loss implementation does not support mask
        loss = energy_score_loss(samples=samples, target=future_target)

        if torch.isnan(loss):
            raise Exception("Loss is NaN, training stopped.")

        self.log(
            f"{name}_loss",
            loss.detach().item(),
            batch_size=B,
            prog_bar=True,
            on_epoch=True,
        )

        return loss


class EngressionNeuralForecastModel(NeuralForecastModel):
    """
    Custom Darts Wrapper for Engression + NeuralForecast models.
    This replaces `_NeuralForecastModule` with `_EngressionPLModule` to ensure
    the custom Energy Score training logic is executed.
    """

    @property
    def supports_probabilistic_prediction(self) -> bool:
        return True

    def _create_model(self, train_sample: TorchTrainingSample) -> LightningModule:
        (
            past_target,
            past_covariates,
            historic_future_covariates,
            future_covariates,
            static_covariates,
            future_target,
        ) = train_sample

        n_past_covs, n_future_covs, n_stat_covs = 0, 0, 0
        if future_covariates is not None:
            n_future_covs = future_covariates.shape[1]
        if past_covariates is not None:
            n_past_covs = past_covariates.shape[1]
        if static_covariates is not None:
            n_stat_covs = static_covariates.shape[1]

        pl_module_params = self.pl_module_params or {}
        pl_module = _EngressionPLModule(
            nf_model_class=self.nf_model_class,
            nf_model_params=self.nf_model_params,
            n_past_covs=n_past_covs,
            n_future_covs=n_future_covs,
            n_stat_covs=n_stat_covs,
            **pl_module_params,
        )

        # Explicitly configure the darts_module references in the base model and noise layer
        pl_module.nf.__dict__["darts_module"] = pl_module
        if hasattr(pl_module.nf, "noise_layer") and pl_module.nf.noise_layer is not None:
            pl_module.nf.noise_layer.__dict__["darts_module"] = pl_module

        return pl_module
